default['install']['bin_dir']         = '/usr/local/bin'
default['install']['nginx_bin']       = '/usr/local/aluxa/nginx/sbin/nginx'
default['install']['luajit_bin']      = '/usr/local/aluxa/luajit/bin/luajit'
default['install']['luarocks_bin']    = '/usr/local/aluxa/luajit/bin/luarocks'
default['install']['aluxa_bin']       = 'bin/aluxa-tools'
default['install']['skills_dir']      = '/usr/local/aluxa/skills'
default['install']['skill_tpl_dir']   = 'skill_tpl'
